Project3/learning_log_pipenv/learning_log_pipenv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users_app.urls')),
    path('', include('learning_logs_app.urls')),
]

Project3/learning_log_pipenv/learning_logs_app/urls.py
""" Defines URL patterns for learning_logs_app. """

from django.urls import path
from . import views

app_name = 'learning_logs_app'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),

    # Show all topics
    path('topics/', views.topics, name='topics'),
    
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
]

Project3/learning_log_pipenv/users_app/urls.py
""" Defines URL patterns for users_app """

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views 

app_name = 'users_app'
urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name='users_app/login.html'), name='login'),

    # Logout page
    path('logout/', LogoutView.as_view(template_name='users_app/logout.html'), name='logout'),
]

Project3/learning_log_pipenv/learning_logs_app/models.py
from django.db import models

class Topic(models.Model):
    """ A Topic the user is learning about """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ Return a string representation of the model. """
        return self.text

class Entry(models.Model):
    """ Something specific learned about a topic """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """ Return a string representation of the model. """
        return self.text[:50] + "..."

Project3/learning_log_pipenv/users_app/models.py
from django.db import models

# Create your models here.

Project3/learning_log_pipenv/learning_logs_app/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}
        

Project3/learning_log_pipenv/learning_logs_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """ The home page for Learning Log """
    return render(request, 'learning_logs_app/index.html')

def topics(request):
    """ Show all topics. """
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs_app/topics.html', context)

def topic(request, topic_id):
    """ Show a single topic and all its entries. """
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs_app/topic.html', context)

def new_topic(request):
    """ Add a new topic """
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topics'))

    context = {'form': form}
    return render(request, 'learning_logs_app/new_topic.html', context)

def new_entry(request, topic_id):
    """ Add a new entry for a particular topic. """
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; create a blank form.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topic', args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs_app/new_entry.html', context)

def edit_entry(request, entry_id):
    """ Edit an existing entry. """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        #Initial requeest; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topic', args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form,}
    return render(request, 'learning_logs_app/edit_entry.html', context)

Project3/learning_log_pipenv/users_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout

def logout_view(request):
    """ Log the user out """
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs_app:index'))

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/base.html
<p>
    <a href="{% url 'learning_logs_app:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs_app:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
      <a href="{% url 'users_app:login' %}">log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/edit_entry.html
{% extends "learning_logs_app/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs_app:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs_app:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">save changes</button>
  </form>

  {% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/index.html
{% extends "learning_logs_app/base.html" %}

{% block content %}
    <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/new_entry.html
{% extends "learning_logs_app/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs_app:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs_app:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
  </form>

{% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/new_topic.html
{% extends "learning_logs_app/base.html" %}

{% block content %}
  <p>Add a topic:</p>
  <form action="{% url 'learning_logs_app:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
  </form>

{% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/topic.html
{% extends 'learning_logs_app/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
  <a href="{% url 'learning_logs_app:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
{% for entry in entries %}
<li>
    <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ entry.text|linebreaks }}</p>
    <p>
      <a href="{% url 'learning_logs_app:edit_entry' entry.id %}">edit entry</a>
    </p>
</li>
{% empty %}
  <li>
      There are no entries for this topic yet.
  </li>
{% endfor %}
</ul>

{% endblock content %}

Project3/learning_log_pipenv/learning_logs_app/templates/learning_logs_app/topics.html
{% extends "learning_logs_app/base.html" %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs_app:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs_app:new_topic' %}">Add a new topic:</a>
  
{% endblock content %}

Project3/learning_log_pipenv/users_app/templates/users_app/login.html
{% extends "learning_logs_app/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'users_app:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs_app:index' %}" />
</form>

{% endblock content %}